import type { SubmissionType } from "@/types/database";

export const TICKET_GOAL = 1000;

export const POINTS = {
  poster: 10,
  event: 150,
  social: 20,
} as const;

export function pointsFor(type: SubmissionType): number {
  return POINTS[type] ?? 0;
}

export const TYPE_LABEL: Record<SubmissionType, string> = {
  poster: "Postering",
  event: "Event Promo",
  social: "Social Post",
};

export const SOCIAL_PLATFORMS = [
  { value: "facebook", label: "Facebook" },
  { value: "instagram", label: "Instagram" },
  { value: "tiktok", label: "TikTok" },
  { value: "reddit", label: "Reddit" },
  { value: "x", label: "X" },
  { value: "other", label: "Other" },
] as const;

export type SocialPlatformValue = (typeof SOCIAL_PLATFORMS)[number]["value"];

export const TARGET_CITY_GROUPS = [
  {
    region: "New York — Cities",
    cities: [
      "Buffalo",
      "Rochester",
      "Syracuse",
      "Ithaca",
      "Niagara Falls",
      "Geneva",
      "Canandaigua",
      "Auburn",
      "Cortland",
      "Elmira",
      "Hornell",
      "Olean",
      "Jamestown",
      "Dunkirk",
      "East Aurora",
      "Lockport",
      "Batavia",
      "Watertown",
      "Albany",
      "Schenectady",
      "Troy",
      "Binghamton",
      "Utica",
      "Saratoga Springs",
      "Plattsburgh",
      "Oneonta",
    ],
  },
  {
    region: "New York — Colleges",
    cities: [
      "University at Buffalo",
      "Buffalo State",
      "Canisius University",
      "University of Rochester",
      "RIT",
      "Nazareth University",
      "Syracuse University",
      "Cornell University",
      "Ithaca College",
      "SUNY Geneseo",
      "SUNY Brockport",
      "SUNY Fredonia",
      "St. Bonaventure",
      "Houghton University",
      "Hobart & William Smith",
      "Colgate University",
      "RPI",
      "SUNY Binghamton",
      "SUNY Albany",
      "SUNY Oswego",
      "SUNY Cortland",
      "SUNY Oneonta",
      "Skidmore College",
    ],
  },
  {
    region: "Ohio — Cities",
    cities: [
      "Cleveland",
      "Akron",
      "Canton",
      "Toledo",
      "Youngstown",
      "Lima, OH",
      "Mansfield, OH",
      "Sandusky",
      "Lorain",
      "Findlay",
      "Warren, OH",
    ],
  },
  {
    region: "Ohio — Colleges",
    cities: [
      "Case Western Reserve",
      "Cleveland State",
      "John Carroll University",
      "University of Akron",
      "Kent State",
      "Bowling Green State",
      "University of Toledo",
      "Youngstown State",
      "Oberlin College",
      "College of Wooster",
      "Baldwin Wallace",
      "Ashland University",
      "University of Findlay",
      "Mount Union",
    ],
  },
  {
    region: "Pennsylvania — Cities",
    cities: [
      "Pittsburgh",
      "Erie, PA",
      "Altoona, PA",
      "Johnstown, PA",
      "Meadville, PA",
      "Bradford, PA",
      "Warren, PA",
      "Beaver Falls, PA",
      "Butler, PA",
      "Sharon, PA",
      "New Castle, PA",
      "Oil City, PA",
      "Indiana, PA",
    ],
  },
  {
    region: "Pennsylvania — Colleges",
    cities: [
      "University of Pittsburgh",
      "Carnegie Mellon",
      "Duquesne University",
      "Robert Morris University",
      "Penn State Behrend",
      "Mercyhurst University",
      "Gannon University",
      "Edinboro University",
      "Allegheny College",
      "Grove City College",
      "Slippery Rock",
      "Westminster College",
      "Geneva College",
      "Saint Vincent College",
      "Washington & Jefferson",
      "IUP",
    ],
  },
  {
    region: "Ontario — Cities",
    cities: [
      "Toronto",
      "Hamilton, ON",
      "Mississauga",
      "Burlington, ON",
      "Oakville",
      "St. Catharines",
      "Niagara Falls, ON",
      "Welland",
      "Fort Erie",
      "Brantford",
      "Kitchener",
      "Waterloo, ON",
      "Cambridge, ON",
      "Guelph",
      "London, ON",
      "Windsor",
      "Kingston",
      "Oshawa",
      "Barrie",
      "Peterborough",
      "Sarnia",
      "Chatham",
    ],
  },
  {
    region: "Ontario — Colleges",
    cities: [
      "University of Toronto",
      "York University",
      "Toronto Metropolitan University",
      "OCAD University",
      "McMaster University",
      "University of Waterloo",
      "Wilfrid Laurier",
      "University of Guelph",
      "Western University",
      "Brock University",
      "Niagara College",
      "Conestoga College",
      "Sheridan College",
      "Humber College",
      "Mohawk College",
      "Queen's University",
      "Trent University",
      "Georgian College",
      "Fanshawe College",
      "University of Windsor",
      "St. Clair College",
    ],
  },
] as const;

// Flat list — kept as a derived value for any code that just needs the names
export const TARGET_CITIES = TARGET_CITY_GROUPS.flatMap((g) => g.cities);
